spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://twm-db.cnu0imq06q2h.eu-west-3.rds.amazonaws.com:3306/TravelWithMeAPI?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:12345678}
    dbcp2:
      max-wait-millis: 30000
      validation-query: /* ping */ select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  profiles:
    active: local

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      TrayectoVueloOrigenUnique: TRAYECTO_VUELO_ORIGEN_UNIQUE
      HotelDireccionUnique: HOTEL_DIRECCION_UNIQUE
      HotelDetallesHotelUnique: HOTEL_DETALLES_HOTEL_UNIQUE
